// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wishlist-wrangler-api/ent/loginrequest"
	"wishlist-wrangler-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginRequestDelete is the builder for deleting a LoginRequest entity.
type LoginRequestDelete struct {
	config
	hooks    []Hook
	mutation *LoginRequestMutation
}

// Where appends a list predicates to the LoginRequestDelete builder.
func (lrd *LoginRequestDelete) Where(ps ...predicate.LoginRequest) *LoginRequestDelete {
	lrd.mutation.Where(ps...)
	return lrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lrd *LoginRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lrd.sqlExec, lrd.mutation, lrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lrd *LoginRequestDelete) ExecX(ctx context.Context) int {
	n, err := lrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lrd *LoginRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(loginrequest.Table, sqlgraph.NewFieldSpec(loginrequest.FieldID, field.TypeUUID))
	if ps := lrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lrd.mutation.done = true
	return affected, err
}

// LoginRequestDeleteOne is the builder for deleting a single LoginRequest entity.
type LoginRequestDeleteOne struct {
	lrd *LoginRequestDelete
}

// Where appends a list predicates to the LoginRequestDelete builder.
func (lrdo *LoginRequestDeleteOne) Where(ps ...predicate.LoginRequest) *LoginRequestDeleteOne {
	lrdo.lrd.mutation.Where(ps...)
	return lrdo
}

// Exec executes the deletion query.
func (lrdo *LoginRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := lrdo.lrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{loginrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lrdo *LoginRequestDeleteOne) ExecX(ctx context.Context) {
	if err := lrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
