// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"wishlist-wrangler-api/ent/loginrequest"
	"wishlist-wrangler-api/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// LoginRequestQuery is the builder for querying LoginRequest entities.
type LoginRequestQuery struct {
	config
	ctx        *QueryContext
	order      []loginrequest.OrderOption
	inters     []Interceptor
	predicates []predicate.LoginRequest
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoginRequestQuery builder.
func (lrq *LoginRequestQuery) Where(ps ...predicate.LoginRequest) *LoginRequestQuery {
	lrq.predicates = append(lrq.predicates, ps...)
	return lrq
}

// Limit the number of records to be returned by this query.
func (lrq *LoginRequestQuery) Limit(limit int) *LoginRequestQuery {
	lrq.ctx.Limit = &limit
	return lrq
}

// Offset to start from.
func (lrq *LoginRequestQuery) Offset(offset int) *LoginRequestQuery {
	lrq.ctx.Offset = &offset
	return lrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lrq *LoginRequestQuery) Unique(unique bool) *LoginRequestQuery {
	lrq.ctx.Unique = &unique
	return lrq
}

// Order specifies how the records should be ordered.
func (lrq *LoginRequestQuery) Order(o ...loginrequest.OrderOption) *LoginRequestQuery {
	lrq.order = append(lrq.order, o...)
	return lrq
}

// First returns the first LoginRequest entity from the query.
// Returns a *NotFoundError when no LoginRequest was found.
func (lrq *LoginRequestQuery) First(ctx context.Context) (*LoginRequest, error) {
	nodes, err := lrq.Limit(1).All(setContextOp(ctx, lrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loginrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lrq *LoginRequestQuery) FirstX(ctx context.Context) *LoginRequest {
	node, err := lrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoginRequest ID from the query.
// Returns a *NotFoundError when no LoginRequest ID was found.
func (lrq *LoginRequestQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lrq.Limit(1).IDs(setContextOp(ctx, lrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loginrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lrq *LoginRequestQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := lrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoginRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LoginRequest entity is found.
// Returns a *NotFoundError when no LoginRequest entities are found.
func (lrq *LoginRequestQuery) Only(ctx context.Context) (*LoginRequest, error) {
	nodes, err := lrq.Limit(2).All(setContextOp(ctx, lrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loginrequest.Label}
	default:
		return nil, &NotSingularError{loginrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lrq *LoginRequestQuery) OnlyX(ctx context.Context) *LoginRequest {
	node, err := lrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoginRequest ID in the query.
// Returns a *NotSingularError when more than one LoginRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (lrq *LoginRequestQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lrq.Limit(2).IDs(setContextOp(ctx, lrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loginrequest.Label}
	default:
		err = &NotSingularError{loginrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lrq *LoginRequestQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := lrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoginRequests.
func (lrq *LoginRequestQuery) All(ctx context.Context) ([]*LoginRequest, error) {
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryAll)
	if err := lrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LoginRequest, *LoginRequestQuery]()
	return withInterceptors[[]*LoginRequest](ctx, lrq, qr, lrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lrq *LoginRequestQuery) AllX(ctx context.Context) []*LoginRequest {
	nodes, err := lrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoginRequest IDs.
func (lrq *LoginRequestQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if lrq.ctx.Unique == nil && lrq.path != nil {
		lrq.Unique(true)
	}
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryIDs)
	if err = lrq.Select(loginrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lrq *LoginRequestQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := lrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lrq *LoginRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryCount)
	if err := lrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lrq, querierCount[*LoginRequestQuery](), lrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lrq *LoginRequestQuery) CountX(ctx context.Context) int {
	count, err := lrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lrq *LoginRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryExist)
	switch _, err := lrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lrq *LoginRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := lrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoginRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lrq *LoginRequestQuery) Clone() *LoginRequestQuery {
	if lrq == nil {
		return nil
	}
	return &LoginRequestQuery{
		config:     lrq.config,
		ctx:        lrq.ctx.Clone(),
		order:      append([]loginrequest.OrderOption{}, lrq.order...),
		inters:     append([]Interceptor{}, lrq.inters...),
		predicates: append([]predicate.LoginRequest{}, lrq.predicates...),
		// clone intermediate query.
		sql:  lrq.sql.Clone(),
		path: lrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserId uuid.UUID `json:"userId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoginRequest.Query().
//		GroupBy(loginrequest.FieldUserId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lrq *LoginRequestQuery) GroupBy(field string, fields ...string) *LoginRequestGroupBy {
	lrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LoginRequestGroupBy{build: lrq}
	grbuild.flds = &lrq.ctx.Fields
	grbuild.label = loginrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserId uuid.UUID `json:"userId,omitempty"`
//	}
//
//	client.LoginRequest.Query().
//		Select(loginrequest.FieldUserId).
//		Scan(ctx, &v)
func (lrq *LoginRequestQuery) Select(fields ...string) *LoginRequestSelect {
	lrq.ctx.Fields = append(lrq.ctx.Fields, fields...)
	sbuild := &LoginRequestSelect{LoginRequestQuery: lrq}
	sbuild.label = loginrequest.Label
	sbuild.flds, sbuild.scan = &lrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LoginRequestSelect configured with the given aggregations.
func (lrq *LoginRequestQuery) Aggregate(fns ...AggregateFunc) *LoginRequestSelect {
	return lrq.Select().Aggregate(fns...)
}

func (lrq *LoginRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lrq); err != nil {
				return err
			}
		}
	}
	for _, f := range lrq.ctx.Fields {
		if !loginrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lrq.path != nil {
		prev, err := lrq.path(ctx)
		if err != nil {
			return err
		}
		lrq.sql = prev
	}
	return nil
}

func (lrq *LoginRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LoginRequest, error) {
	var (
		nodes = []*LoginRequest{}
		_spec = lrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LoginRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LoginRequest{config: lrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lrq *LoginRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lrq.querySpec()
	_spec.Node.Columns = lrq.ctx.Fields
	if len(lrq.ctx.Fields) > 0 {
		_spec.Unique = lrq.ctx.Unique != nil && *lrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lrq.driver, _spec)
}

func (lrq *LoginRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(loginrequest.Table, loginrequest.Columns, sqlgraph.NewFieldSpec(loginrequest.FieldID, field.TypeUUID))
	_spec.From = lrq.sql
	if unique := lrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lrq.path != nil {
		_spec.Unique = true
	}
	if fields := lrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginrequest.FieldID)
		for i := range fields {
			if fields[i] != loginrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lrq *LoginRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lrq.driver.Dialect())
	t1 := builder.Table(loginrequest.Table)
	columns := lrq.ctx.Fields
	if len(columns) == 0 {
		columns = loginrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lrq.sql != nil {
		selector = lrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lrq.ctx.Unique != nil && *lrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lrq.predicates {
		p(selector)
	}
	for _, p := range lrq.order {
		p(selector)
	}
	if offset := lrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoginRequestGroupBy is the group-by builder for LoginRequest entities.
type LoginRequestGroupBy struct {
	selector
	build *LoginRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lrgb *LoginRequestGroupBy) Aggregate(fns ...AggregateFunc) *LoginRequestGroupBy {
	lrgb.fns = append(lrgb.fns, fns...)
	return lrgb
}

// Scan applies the selector query and scans the result into the given value.
func (lrgb *LoginRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrgb.build.ctx, ent.OpQueryGroupBy)
	if err := lrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginRequestQuery, *LoginRequestGroupBy](ctx, lrgb.build, lrgb, lrgb.build.inters, v)
}

func (lrgb *LoginRequestGroupBy) sqlScan(ctx context.Context, root *LoginRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lrgb.fns))
	for _, fn := range lrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lrgb.flds)+len(lrgb.fns))
		for _, f := range *lrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LoginRequestSelect is the builder for selecting fields of LoginRequest entities.
type LoginRequestSelect struct {
	*LoginRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lrs *LoginRequestSelect) Aggregate(fns ...AggregateFunc) *LoginRequestSelect {
	lrs.fns = append(lrs.fns, fns...)
	return lrs
}

// Scan applies the selector query and scans the result into the given value.
func (lrs *LoginRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrs.ctx, ent.OpQuerySelect)
	if err := lrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginRequestQuery, *LoginRequestSelect](ctx, lrs.LoginRequestQuery, lrs, lrs.inters, v)
}

func (lrs *LoginRequestSelect) sqlScan(ctx context.Context, root *LoginRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lrs.fns))
	for _, fn := range lrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
