// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wishlist-wrangler-api/ent/wishlisttemplate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// WishlistTemplate is the model entity for the WishlistTemplate schema.
type WishlistTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status wishlisttemplate.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WishlistTemplateQuery when eager-loading is set.
	Edges                WishlistTemplateEdges `json:"edges"`
	wishlist_template_id *uuid.UUID
	selectValues         sql.SelectValues
}

// WishlistTemplateEdges holds the relations/edges for other nodes in the graph.
type WishlistTemplateEdges struct {
	// CreatorId holds the value of the creatorId edge.
	CreatorId []*User `json:"creatorId,omitempty"`
	// Sections holds the value of the sections edge.
	Sections []*WishlistTemplateSection `json:"sections,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CreatorIdOrErr returns the CreatorId value or an error if the edge
// was not loaded in eager-loading.
func (e WishlistTemplateEdges) CreatorIdOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.CreatorId, nil
	}
	return nil, &NotLoadedError{edge: "creatorId"}
}

// SectionsOrErr returns the Sections value or an error if the edge
// was not loaded in eager-loading.
func (e WishlistTemplateEdges) SectionsOrErr() ([]*WishlistTemplateSection, error) {
	if e.loadedTypes[1] {
		return e.Sections, nil
	}
	return nil, &NotLoadedError{edge: "sections"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WishlistTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wishlisttemplate.FieldTitle, wishlisttemplate.FieldDescription, wishlisttemplate.FieldStatus:
			values[i] = new(sql.NullString)
		case wishlisttemplate.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case wishlisttemplate.FieldID:
			values[i] = new(uuid.UUID)
		case wishlisttemplate.ForeignKeys[0]: // wishlist_template_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WishlistTemplate fields.
func (wt *WishlistTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wishlisttemplate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				wt.ID = *value
			}
		case wishlisttemplate.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				wt.Title = value.String
			}
		case wishlisttemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wt.CreatedAt = value.Time
			}
		case wishlisttemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				wt.Description = value.String
			}
		case wishlisttemplate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				wt.Status = wishlisttemplate.Status(value.String)
			}
		case wishlisttemplate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field wishlist_template_id", values[i])
			} else if value.Valid {
				wt.wishlist_template_id = new(uuid.UUID)
				*wt.wishlist_template_id = *value.S.(*uuid.UUID)
			}
		default:
			wt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WishlistTemplate.
// This includes values selected through modifiers, order, etc.
func (wt *WishlistTemplate) Value(name string) (ent.Value, error) {
	return wt.selectValues.Get(name)
}

// QueryCreatorId queries the "creatorId" edge of the WishlistTemplate entity.
func (wt *WishlistTemplate) QueryCreatorId() *UserQuery {
	return NewWishlistTemplateClient(wt.config).QueryCreatorId(wt)
}

// QuerySections queries the "sections" edge of the WishlistTemplate entity.
func (wt *WishlistTemplate) QuerySections() *WishlistTemplateSectionQuery {
	return NewWishlistTemplateClient(wt.config).QuerySections(wt)
}

// Update returns a builder for updating this WishlistTemplate.
// Note that you need to call WishlistTemplate.Unwrap() before calling this method if this WishlistTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (wt *WishlistTemplate) Update() *WishlistTemplateUpdateOne {
	return NewWishlistTemplateClient(wt.config).UpdateOne(wt)
}

// Unwrap unwraps the WishlistTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wt *WishlistTemplate) Unwrap() *WishlistTemplate {
	_tx, ok := wt.config.driver.(*txDriver)
	if !ok {
		panic("ent: WishlistTemplate is not a transactional entity")
	}
	wt.config.driver = _tx.drv
	return wt
}

// String implements the fmt.Stringer.
func (wt *WishlistTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("WishlistTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wt.ID))
	builder.WriteString("title=")
	builder.WriteString(wt.Title)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(wt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(wt.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", wt.Status))
	builder.WriteByte(')')
	return builder.String()
}

// WishlistTemplates is a parsable slice of WishlistTemplate.
type WishlistTemplates []*WishlistTemplate
