// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"wishlist-wrangler-api/ent/predicate"
	"wishlist-wrangler-api/ent/user"
	"wishlist-wrangler-api/ent/wishlist"
	"wishlist-wrangler-api/ent/wishlistsection"
	"wishlist-wrangler-api/ent/wishlisttemplate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WishlistQuery is the builder for querying Wishlist entities.
type WishlistQuery struct {
	config
	ctx            *QueryContext
	order          []wishlist.OrderOption
	inters         []Interceptor
	predicates     []predicate.Wishlist
	withCreatorId  *UserQuery
	withTemplateId *WishlistTemplateQuery
	withSections   *WishlistSectionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WishlistQuery builder.
func (wq *WishlistQuery) Where(ps ...predicate.Wishlist) *WishlistQuery {
	wq.predicates = append(wq.predicates, ps...)
	return wq
}

// Limit the number of records to be returned by this query.
func (wq *WishlistQuery) Limit(limit int) *WishlistQuery {
	wq.ctx.Limit = &limit
	return wq
}

// Offset to start from.
func (wq *WishlistQuery) Offset(offset int) *WishlistQuery {
	wq.ctx.Offset = &offset
	return wq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wq *WishlistQuery) Unique(unique bool) *WishlistQuery {
	wq.ctx.Unique = &unique
	return wq
}

// Order specifies how the records should be ordered.
func (wq *WishlistQuery) Order(o ...wishlist.OrderOption) *WishlistQuery {
	wq.order = append(wq.order, o...)
	return wq
}

// QueryCreatorId chains the current query on the "creatorId" edge.
func (wq *WishlistQuery) QueryCreatorId() *UserQuery {
	query := (&UserClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wishlist.Table, wishlist.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wishlist.CreatorIdTable, wishlist.CreatorIdColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTemplateId chains the current query on the "templateId" edge.
func (wq *WishlistQuery) QueryTemplateId() *WishlistTemplateQuery {
	query := (&WishlistTemplateClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wishlist.Table, wishlist.FieldID, selector),
			sqlgraph.To(wishlisttemplate.Table, wishlisttemplate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wishlist.TemplateIdTable, wishlist.TemplateIdColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySections chains the current query on the "sections" edge.
func (wq *WishlistQuery) QuerySections() *WishlistSectionQuery {
	query := (&WishlistSectionClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wishlist.Table, wishlist.FieldID, selector),
			sqlgraph.To(wishlistsection.Table, wishlistsection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wishlist.SectionsTable, wishlist.SectionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Wishlist entity from the query.
// Returns a *NotFoundError when no Wishlist was found.
func (wq *WishlistQuery) First(ctx context.Context) (*Wishlist, error) {
	nodes, err := wq.Limit(1).All(setContextOp(ctx, wq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wishlist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wq *WishlistQuery) FirstX(ctx context.Context) *Wishlist {
	node, err := wq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Wishlist ID from the query.
// Returns a *NotFoundError when no Wishlist ID was found.
func (wq *WishlistQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(1).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wishlist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wq *WishlistQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := wq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Wishlist entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Wishlist entity is found.
// Returns a *NotFoundError when no Wishlist entities are found.
func (wq *WishlistQuery) Only(ctx context.Context) (*Wishlist, error) {
	nodes, err := wq.Limit(2).All(setContextOp(ctx, wq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wishlist.Label}
	default:
		return nil, &NotSingularError{wishlist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wq *WishlistQuery) OnlyX(ctx context.Context) *Wishlist {
	node, err := wq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Wishlist ID in the query.
// Returns a *NotSingularError when more than one Wishlist ID is found.
// Returns a *NotFoundError when no entities are found.
func (wq *WishlistQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(2).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wishlist.Label}
	default:
		err = &NotSingularError{wishlist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wq *WishlistQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := wq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Wishlists.
func (wq *WishlistQuery) All(ctx context.Context) ([]*Wishlist, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryAll)
	if err := wq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Wishlist, *WishlistQuery]()
	return withInterceptors[[]*Wishlist](ctx, wq, qr, wq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wq *WishlistQuery) AllX(ctx context.Context) []*Wishlist {
	nodes, err := wq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Wishlist IDs.
func (wq *WishlistQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if wq.ctx.Unique == nil && wq.path != nil {
		wq.Unique(true)
	}
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryIDs)
	if err = wq.Select(wishlist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wq *WishlistQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := wq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wq *WishlistQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryCount)
	if err := wq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wq, querierCount[*WishlistQuery](), wq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wq *WishlistQuery) CountX(ctx context.Context) int {
	count, err := wq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wq *WishlistQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryExist)
	switch _, err := wq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wq *WishlistQuery) ExistX(ctx context.Context) bool {
	exist, err := wq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WishlistQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wq *WishlistQuery) Clone() *WishlistQuery {
	if wq == nil {
		return nil
	}
	return &WishlistQuery{
		config:         wq.config,
		ctx:            wq.ctx.Clone(),
		order:          append([]wishlist.OrderOption{}, wq.order...),
		inters:         append([]Interceptor{}, wq.inters...),
		predicates:     append([]predicate.Wishlist{}, wq.predicates...),
		withCreatorId:  wq.withCreatorId.Clone(),
		withTemplateId: wq.withTemplateId.Clone(),
		withSections:   wq.withSections.Clone(),
		// clone intermediate query.
		sql:  wq.sql.Clone(),
		path: wq.path,
	}
}

// WithCreatorId tells the query-builder to eager-load the nodes that are connected to
// the "creatorId" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WishlistQuery) WithCreatorId(opts ...func(*UserQuery)) *WishlistQuery {
	query := (&UserClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withCreatorId = query
	return wq
}

// WithTemplateId tells the query-builder to eager-load the nodes that are connected to
// the "templateId" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WishlistQuery) WithTemplateId(opts ...func(*WishlistTemplateQuery)) *WishlistQuery {
	query := (&WishlistTemplateClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withTemplateId = query
	return wq
}

// WithSections tells the query-builder to eager-load the nodes that are connected to
// the "sections" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WishlistQuery) WithSections(opts ...func(*WishlistSectionQuery)) *WishlistQuery {
	query := (&WishlistSectionClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withSections = query
	return wq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Wishlist.Query().
//		GroupBy(wishlist.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wq *WishlistQuery) GroupBy(field string, fields ...string) *WishlistGroupBy {
	wq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WishlistGroupBy{build: wq}
	grbuild.flds = &wq.ctx.Fields
	grbuild.label = wishlist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Wishlist.Query().
//		Select(wishlist.FieldTitle).
//		Scan(ctx, &v)
func (wq *WishlistQuery) Select(fields ...string) *WishlistSelect {
	wq.ctx.Fields = append(wq.ctx.Fields, fields...)
	sbuild := &WishlistSelect{WishlistQuery: wq}
	sbuild.label = wishlist.Label
	sbuild.flds, sbuild.scan = &wq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WishlistSelect configured with the given aggregations.
func (wq *WishlistQuery) Aggregate(fns ...AggregateFunc) *WishlistSelect {
	return wq.Select().Aggregate(fns...)
}

func (wq *WishlistQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wq); err != nil {
				return err
			}
		}
	}
	for _, f := range wq.ctx.Fields {
		if !wishlist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wq.path != nil {
		prev, err := wq.path(ctx)
		if err != nil {
			return err
		}
		wq.sql = prev
	}
	return nil
}

func (wq *WishlistQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Wishlist, error) {
	var (
		nodes       = []*Wishlist{}
		_spec       = wq.querySpec()
		loadedTypes = [3]bool{
			wq.withCreatorId != nil,
			wq.withTemplateId != nil,
			wq.withSections != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Wishlist).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Wishlist{config: wq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wq.withCreatorId; query != nil {
		if err := wq.loadCreatorId(ctx, query, nodes,
			func(n *Wishlist) { n.Edges.CreatorId = []*User{} },
			func(n *Wishlist, e *User) { n.Edges.CreatorId = append(n.Edges.CreatorId, e) }); err != nil {
			return nil, err
		}
	}
	if query := wq.withTemplateId; query != nil {
		if err := wq.loadTemplateId(ctx, query, nodes,
			func(n *Wishlist) { n.Edges.TemplateId = []*WishlistTemplate{} },
			func(n *Wishlist, e *WishlistTemplate) { n.Edges.TemplateId = append(n.Edges.TemplateId, e) }); err != nil {
			return nil, err
		}
	}
	if query := wq.withSections; query != nil {
		if err := wq.loadSections(ctx, query, nodes,
			func(n *Wishlist) { n.Edges.Sections = []*WishlistSection{} },
			func(n *Wishlist, e *WishlistSection) { n.Edges.Sections = append(n.Edges.Sections, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wq *WishlistQuery) loadCreatorId(ctx context.Context, query *UserQuery, nodes []*Wishlist, init func(*Wishlist), assign func(*Wishlist, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Wishlist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wishlist.CreatorIdColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.wishlist_creator_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "wishlist_creator_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wishlist_creator_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wq *WishlistQuery) loadTemplateId(ctx context.Context, query *WishlistTemplateQuery, nodes []*Wishlist, init func(*Wishlist), assign func(*Wishlist, *WishlistTemplate)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Wishlist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WishlistTemplate(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wishlist.TemplateIdColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.wishlist_template_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "wishlist_template_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wishlist_template_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wq *WishlistQuery) loadSections(ctx context.Context, query *WishlistSectionQuery, nodes []*Wishlist, init func(*Wishlist), assign func(*Wishlist, *WishlistSection)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Wishlist)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WishlistSection(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wishlist.SectionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.wishlist_sections
		if fk == nil {
			return fmt.Errorf(`foreign-key "wishlist_sections" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wishlist_sections" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (wq *WishlistQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wq.querySpec()
	_spec.Node.Columns = wq.ctx.Fields
	if len(wq.ctx.Fields) > 0 {
		_spec.Unique = wq.ctx.Unique != nil && *wq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wq.driver, _spec)
}

func (wq *WishlistQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wishlist.Table, wishlist.Columns, sqlgraph.NewFieldSpec(wishlist.FieldID, field.TypeUUID))
	_spec.From = wq.sql
	if unique := wq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wq.path != nil {
		_spec.Unique = true
	}
	if fields := wq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wishlist.FieldID)
		for i := range fields {
			if fields[i] != wishlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wq *WishlistQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wq.driver.Dialect())
	t1 := builder.Table(wishlist.Table)
	columns := wq.ctx.Fields
	if len(columns) == 0 {
		columns = wishlist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wq.sql != nil {
		selector = wq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wq.ctx.Unique != nil && *wq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wq.predicates {
		p(selector)
	}
	for _, p := range wq.order {
		p(selector)
	}
	if offset := wq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WishlistGroupBy is the group-by builder for Wishlist entities.
type WishlistGroupBy struct {
	selector
	build *WishlistQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wgb *WishlistGroupBy) Aggregate(fns ...AggregateFunc) *WishlistGroupBy {
	wgb.fns = append(wgb.fns, fns...)
	return wgb
}

// Scan applies the selector query and scans the result into the given value.
func (wgb *WishlistGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wgb.build.ctx, ent.OpQueryGroupBy)
	if err := wgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WishlistQuery, *WishlistGroupBy](ctx, wgb.build, wgb, wgb.build.inters, v)
}

func (wgb *WishlistGroupBy) sqlScan(ctx context.Context, root *WishlistQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wgb.fns))
	for _, fn := range wgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wgb.flds)+len(wgb.fns))
		for _, f := range *wgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WishlistSelect is the builder for selecting fields of Wishlist entities.
type WishlistSelect struct {
	*WishlistQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ws *WishlistSelect) Aggregate(fns ...AggregateFunc) *WishlistSelect {
	ws.fns = append(ws.fns, fns...)
	return ws
}

// Scan applies the selector query and scans the result into the given value.
func (ws *WishlistSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ws.ctx, ent.OpQuerySelect)
	if err := ws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WishlistQuery, *WishlistSelect](ctx, ws.WishlistQuery, ws, ws.inters, v)
}

func (ws *WishlistSelect) sqlScan(ctx context.Context, root *WishlistQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ws.fns))
	for _, fn := range ws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
