// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wishlist-wrangler-api/ent/predicate"
	"wishlist-wrangler-api/ent/wishlistsection"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WishlistSectionDelete is the builder for deleting a WishlistSection entity.
type WishlistSectionDelete struct {
	config
	hooks    []Hook
	mutation *WishlistSectionMutation
}

// Where appends a list predicates to the WishlistSectionDelete builder.
func (wsd *WishlistSectionDelete) Where(ps ...predicate.WishlistSection) *WishlistSectionDelete {
	wsd.mutation.Where(ps...)
	return wsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wsd *WishlistSectionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wsd.sqlExec, wsd.mutation, wsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wsd *WishlistSectionDelete) ExecX(ctx context.Context) int {
	n, err := wsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wsd *WishlistSectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(wishlistsection.Table, sqlgraph.NewFieldSpec(wishlistsection.FieldID, field.TypeUUID))
	if ps := wsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wsd.mutation.done = true
	return affected, err
}

// WishlistSectionDeleteOne is the builder for deleting a single WishlistSection entity.
type WishlistSectionDeleteOne struct {
	wsd *WishlistSectionDelete
}

// Where appends a list predicates to the WishlistSectionDelete builder.
func (wsdo *WishlistSectionDeleteOne) Where(ps ...predicate.WishlistSection) *WishlistSectionDeleteOne {
	wsdo.wsd.mutation.Where(ps...)
	return wsdo
}

// Exec executes the deletion query.
func (wsdo *WishlistSectionDeleteOne) Exec(ctx context.Context) error {
	n, err := wsdo.wsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wishlistsection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wsdo *WishlistSectionDeleteOne) ExecX(ctx context.Context) {
	if err := wsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
