// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wishlist-wrangler-api/ent/wishlisttemplatesection"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// WishlistTemplateSection is the model entity for the WishlistTemplateSection schema.
type WishlistTemplateSection struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// WishlistTemplateID holds the value of the "wishlist_template_id" field.
	WishlistTemplateID uuid.UUID `json:"wishlist_template_id,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WishlistTemplateSection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wishlisttemplatesection.FieldTitle:
			values[i] = new(sql.NullString)
		case wishlisttemplatesection.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case wishlisttemplatesection.FieldID, wishlisttemplatesection.FieldWishlistTemplateID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WishlistTemplateSection fields.
func (wts *WishlistTemplateSection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wishlisttemplatesection.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				wts.ID = *value
			}
		case wishlisttemplatesection.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				wts.Title = value.String
			}
		case wishlisttemplatesection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wts.CreatedAt = value.Time
			}
		case wishlisttemplatesection.FieldWishlistTemplateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field wishlist_template_id", values[i])
			} else if value != nil {
				wts.WishlistTemplateID = *value
			}
		default:
			wts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WishlistTemplateSection.
// This includes values selected through modifiers, order, etc.
func (wts *WishlistTemplateSection) Value(name string) (ent.Value, error) {
	return wts.selectValues.Get(name)
}

// Update returns a builder for updating this WishlistTemplateSection.
// Note that you need to call WishlistTemplateSection.Unwrap() before calling this method if this WishlistTemplateSection
// was returned from a transaction, and the transaction was committed or rolled back.
func (wts *WishlistTemplateSection) Update() *WishlistTemplateSectionUpdateOne {
	return NewWishlistTemplateSectionClient(wts.config).UpdateOne(wts)
}

// Unwrap unwraps the WishlistTemplateSection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wts *WishlistTemplateSection) Unwrap() *WishlistTemplateSection {
	_tx, ok := wts.config.driver.(*txDriver)
	if !ok {
		panic("ent: WishlistTemplateSection is not a transactional entity")
	}
	wts.config.driver = _tx.drv
	return wts
}

// String implements the fmt.Stringer.
func (wts *WishlistTemplateSection) String() string {
	var builder strings.Builder
	builder.WriteString("WishlistTemplateSection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wts.ID))
	builder.WriteString("title=")
	builder.WriteString(wts.Title)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(wts.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("wishlist_template_id=")
	builder.WriteString(fmt.Sprintf("%v", wts.WishlistTemplateID))
	builder.WriteByte(')')
	return builder.String()
}

// WishlistTemplateSections is a parsable slice of WishlistTemplateSection.
type WishlistTemplateSections []*WishlistTemplateSection
