// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wishlist-wrangler-api/ent/predicate"
	"wishlist-wrangler-api/ent/wishlist"
	"wishlist-wrangler-api/ent/wishlistsection"
	"wishlist-wrangler-api/ent/wishlisttemplatesection"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WishlistSectionUpdate is the builder for updating WishlistSection entities.
type WishlistSectionUpdate struct {
	config
	hooks    []Hook
	mutation *WishlistSectionMutation
}

// Where appends a list predicates to the WishlistSectionUpdate builder.
func (wsu *WishlistSectionUpdate) Where(ps ...predicate.WishlistSection) *WishlistSectionUpdate {
	wsu.mutation.Where(ps...)
	return wsu
}

// SetType sets the "type" field.
func (wsu *WishlistSectionUpdate) SetType(w wishlistsection.Type) *WishlistSectionUpdate {
	wsu.mutation.SetType(w)
	return wsu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (wsu *WishlistSectionUpdate) SetNillableType(w *wishlistsection.Type) *WishlistSectionUpdate {
	if w != nil {
		wsu.SetType(*w)
	}
	return wsu
}

// SetTextValue sets the "textValue" field.
func (wsu *WishlistSectionUpdate) SetTextValue(s string) *WishlistSectionUpdate {
	wsu.mutation.SetTextValue(s)
	return wsu
}

// SetNillableTextValue sets the "textValue" field if the given value is not nil.
func (wsu *WishlistSectionUpdate) SetNillableTextValue(s *string) *WishlistSectionUpdate {
	if s != nil {
		wsu.SetTextValue(*s)
	}
	return wsu
}

// SetWishlistID sets the "wishlist" edge to the Wishlist entity by ID.
func (wsu *WishlistSectionUpdate) SetWishlistID(id uuid.UUID) *WishlistSectionUpdate {
	wsu.mutation.SetWishlistID(id)
	return wsu
}

// SetNillableWishlistID sets the "wishlist" edge to the Wishlist entity by ID if the given value is not nil.
func (wsu *WishlistSectionUpdate) SetNillableWishlistID(id *uuid.UUID) *WishlistSectionUpdate {
	if id != nil {
		wsu = wsu.SetWishlistID(*id)
	}
	return wsu
}

// SetWishlist sets the "wishlist" edge to the Wishlist entity.
func (wsu *WishlistSectionUpdate) SetWishlist(w *Wishlist) *WishlistSectionUpdate {
	return wsu.SetWishlistID(w.ID)
}

// AddWishlistTemplateSectionIDs adds the "wishlistTemplateSection" edge to the WishlistTemplateSection entity by IDs.
func (wsu *WishlistSectionUpdate) AddWishlistTemplateSectionIDs(ids ...uuid.UUID) *WishlistSectionUpdate {
	wsu.mutation.AddWishlistTemplateSectionIDs(ids...)
	return wsu
}

// AddWishlistTemplateSection adds the "wishlistTemplateSection" edges to the WishlistTemplateSection entity.
func (wsu *WishlistSectionUpdate) AddWishlistTemplateSection(w ...*WishlistTemplateSection) *WishlistSectionUpdate {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsu.AddWishlistTemplateSectionIDs(ids...)
}

// Mutation returns the WishlistSectionMutation object of the builder.
func (wsu *WishlistSectionUpdate) Mutation() *WishlistSectionMutation {
	return wsu.mutation
}

// ClearWishlist clears the "wishlist" edge to the Wishlist entity.
func (wsu *WishlistSectionUpdate) ClearWishlist() *WishlistSectionUpdate {
	wsu.mutation.ClearWishlist()
	return wsu
}

// ClearWishlistTemplateSection clears all "wishlistTemplateSection" edges to the WishlistTemplateSection entity.
func (wsu *WishlistSectionUpdate) ClearWishlistTemplateSection() *WishlistSectionUpdate {
	wsu.mutation.ClearWishlistTemplateSection()
	return wsu
}

// RemoveWishlistTemplateSectionIDs removes the "wishlistTemplateSection" edge to WishlistTemplateSection entities by IDs.
func (wsu *WishlistSectionUpdate) RemoveWishlistTemplateSectionIDs(ids ...uuid.UUID) *WishlistSectionUpdate {
	wsu.mutation.RemoveWishlistTemplateSectionIDs(ids...)
	return wsu
}

// RemoveWishlistTemplateSection removes "wishlistTemplateSection" edges to WishlistTemplateSection entities.
func (wsu *WishlistSectionUpdate) RemoveWishlistTemplateSection(w ...*WishlistTemplateSection) *WishlistSectionUpdate {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsu.RemoveWishlistTemplateSectionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wsu *WishlistSectionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wsu.sqlSave, wsu.mutation, wsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsu *WishlistSectionUpdate) SaveX(ctx context.Context) int {
	affected, err := wsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wsu *WishlistSectionUpdate) Exec(ctx context.Context) error {
	_, err := wsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsu *WishlistSectionUpdate) ExecX(ctx context.Context) {
	if err := wsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wsu *WishlistSectionUpdate) check() error {
	if v, ok := wsu.mutation.GetType(); ok {
		if err := wishlistsection.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "WishlistSection.type": %w`, err)}
		}
	}
	if v, ok := wsu.mutation.TextValue(); ok {
		if err := wishlistsection.TextValueValidator(v); err != nil {
			return &ValidationError{Name: "textValue", err: fmt.Errorf(`ent: validator failed for field "WishlistSection.textValue": %w`, err)}
		}
	}
	return nil
}

func (wsu *WishlistSectionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(wishlistsection.Table, wishlistsection.Columns, sqlgraph.NewFieldSpec(wishlistsection.FieldID, field.TypeUUID))
	if ps := wsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wsu.mutation.GetType(); ok {
		_spec.SetField(wishlistsection.FieldType, field.TypeEnum, value)
	}
	if value, ok := wsu.mutation.TextValue(); ok {
		_spec.SetField(wishlistsection.FieldTextValue, field.TypeString, value)
	}
	if wsu.mutation.WishlistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wishlistsection.WishlistTable,
			Columns: []string{wishlistsection.WishlistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlist.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsu.mutation.WishlistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wishlistsection.WishlistTable,
			Columns: []string{wishlistsection.WishlistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wsu.mutation.WishlistTemplateSectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wishlistsection.WishlistTemplateSectionTable,
			Columns: []string{wishlistsection.WishlistTemplateSectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlisttemplatesection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsu.mutation.RemovedWishlistTemplateSectionIDs(); len(nodes) > 0 && !wsu.mutation.WishlistTemplateSectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wishlistsection.WishlistTemplateSectionTable,
			Columns: []string{wishlistsection.WishlistTemplateSectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlisttemplatesection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsu.mutation.WishlistTemplateSectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wishlistsection.WishlistTemplateSectionTable,
			Columns: []string{wishlistsection.WishlistTemplateSectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlisttemplatesection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wishlistsection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wsu.mutation.done = true
	return n, nil
}

// WishlistSectionUpdateOne is the builder for updating a single WishlistSection entity.
type WishlistSectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WishlistSectionMutation
}

// SetType sets the "type" field.
func (wsuo *WishlistSectionUpdateOne) SetType(w wishlistsection.Type) *WishlistSectionUpdateOne {
	wsuo.mutation.SetType(w)
	return wsuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (wsuo *WishlistSectionUpdateOne) SetNillableType(w *wishlistsection.Type) *WishlistSectionUpdateOne {
	if w != nil {
		wsuo.SetType(*w)
	}
	return wsuo
}

// SetTextValue sets the "textValue" field.
func (wsuo *WishlistSectionUpdateOne) SetTextValue(s string) *WishlistSectionUpdateOne {
	wsuo.mutation.SetTextValue(s)
	return wsuo
}

// SetNillableTextValue sets the "textValue" field if the given value is not nil.
func (wsuo *WishlistSectionUpdateOne) SetNillableTextValue(s *string) *WishlistSectionUpdateOne {
	if s != nil {
		wsuo.SetTextValue(*s)
	}
	return wsuo
}

// SetWishlistID sets the "wishlist" edge to the Wishlist entity by ID.
func (wsuo *WishlistSectionUpdateOne) SetWishlistID(id uuid.UUID) *WishlistSectionUpdateOne {
	wsuo.mutation.SetWishlistID(id)
	return wsuo
}

// SetNillableWishlistID sets the "wishlist" edge to the Wishlist entity by ID if the given value is not nil.
func (wsuo *WishlistSectionUpdateOne) SetNillableWishlistID(id *uuid.UUID) *WishlistSectionUpdateOne {
	if id != nil {
		wsuo = wsuo.SetWishlistID(*id)
	}
	return wsuo
}

// SetWishlist sets the "wishlist" edge to the Wishlist entity.
func (wsuo *WishlistSectionUpdateOne) SetWishlist(w *Wishlist) *WishlistSectionUpdateOne {
	return wsuo.SetWishlistID(w.ID)
}

// AddWishlistTemplateSectionIDs adds the "wishlistTemplateSection" edge to the WishlistTemplateSection entity by IDs.
func (wsuo *WishlistSectionUpdateOne) AddWishlistTemplateSectionIDs(ids ...uuid.UUID) *WishlistSectionUpdateOne {
	wsuo.mutation.AddWishlistTemplateSectionIDs(ids...)
	return wsuo
}

// AddWishlistTemplateSection adds the "wishlistTemplateSection" edges to the WishlistTemplateSection entity.
func (wsuo *WishlistSectionUpdateOne) AddWishlistTemplateSection(w ...*WishlistTemplateSection) *WishlistSectionUpdateOne {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsuo.AddWishlistTemplateSectionIDs(ids...)
}

// Mutation returns the WishlistSectionMutation object of the builder.
func (wsuo *WishlistSectionUpdateOne) Mutation() *WishlistSectionMutation {
	return wsuo.mutation
}

// ClearWishlist clears the "wishlist" edge to the Wishlist entity.
func (wsuo *WishlistSectionUpdateOne) ClearWishlist() *WishlistSectionUpdateOne {
	wsuo.mutation.ClearWishlist()
	return wsuo
}

// ClearWishlistTemplateSection clears all "wishlistTemplateSection" edges to the WishlistTemplateSection entity.
func (wsuo *WishlistSectionUpdateOne) ClearWishlistTemplateSection() *WishlistSectionUpdateOne {
	wsuo.mutation.ClearWishlistTemplateSection()
	return wsuo
}

// RemoveWishlistTemplateSectionIDs removes the "wishlistTemplateSection" edge to WishlistTemplateSection entities by IDs.
func (wsuo *WishlistSectionUpdateOne) RemoveWishlistTemplateSectionIDs(ids ...uuid.UUID) *WishlistSectionUpdateOne {
	wsuo.mutation.RemoveWishlistTemplateSectionIDs(ids...)
	return wsuo
}

// RemoveWishlistTemplateSection removes "wishlistTemplateSection" edges to WishlistTemplateSection entities.
func (wsuo *WishlistSectionUpdateOne) RemoveWishlistTemplateSection(w ...*WishlistTemplateSection) *WishlistSectionUpdateOne {
	ids := make([]uuid.UUID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsuo.RemoveWishlistTemplateSectionIDs(ids...)
}

// Where appends a list predicates to the WishlistSectionUpdate builder.
func (wsuo *WishlistSectionUpdateOne) Where(ps ...predicate.WishlistSection) *WishlistSectionUpdateOne {
	wsuo.mutation.Where(ps...)
	return wsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wsuo *WishlistSectionUpdateOne) Select(field string, fields ...string) *WishlistSectionUpdateOne {
	wsuo.fields = append([]string{field}, fields...)
	return wsuo
}

// Save executes the query and returns the updated WishlistSection entity.
func (wsuo *WishlistSectionUpdateOne) Save(ctx context.Context) (*WishlistSection, error) {
	return withHooks(ctx, wsuo.sqlSave, wsuo.mutation, wsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsuo *WishlistSectionUpdateOne) SaveX(ctx context.Context) *WishlistSection {
	node, err := wsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wsuo *WishlistSectionUpdateOne) Exec(ctx context.Context) error {
	_, err := wsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsuo *WishlistSectionUpdateOne) ExecX(ctx context.Context) {
	if err := wsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wsuo *WishlistSectionUpdateOne) check() error {
	if v, ok := wsuo.mutation.GetType(); ok {
		if err := wishlistsection.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "WishlistSection.type": %w`, err)}
		}
	}
	if v, ok := wsuo.mutation.TextValue(); ok {
		if err := wishlistsection.TextValueValidator(v); err != nil {
			return &ValidationError{Name: "textValue", err: fmt.Errorf(`ent: validator failed for field "WishlistSection.textValue": %w`, err)}
		}
	}
	return nil
}

func (wsuo *WishlistSectionUpdateOne) sqlSave(ctx context.Context) (_node *WishlistSection, err error) {
	if err := wsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wishlistsection.Table, wishlistsection.Columns, sqlgraph.NewFieldSpec(wishlistsection.FieldID, field.TypeUUID))
	id, ok := wsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WishlistSection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wishlistsection.FieldID)
		for _, f := range fields {
			if !wishlistsection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wishlistsection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wsuo.mutation.GetType(); ok {
		_spec.SetField(wishlistsection.FieldType, field.TypeEnum, value)
	}
	if value, ok := wsuo.mutation.TextValue(); ok {
		_spec.SetField(wishlistsection.FieldTextValue, field.TypeString, value)
	}
	if wsuo.mutation.WishlistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wishlistsection.WishlistTable,
			Columns: []string{wishlistsection.WishlistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlist.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsuo.mutation.WishlistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wishlistsection.WishlistTable,
			Columns: []string{wishlistsection.WishlistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wsuo.mutation.WishlistTemplateSectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wishlistsection.WishlistTemplateSectionTable,
			Columns: []string{wishlistsection.WishlistTemplateSectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlisttemplatesection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsuo.mutation.RemovedWishlistTemplateSectionIDs(); len(nodes) > 0 && !wsuo.mutation.WishlistTemplateSectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wishlistsection.WishlistTemplateSectionTable,
			Columns: []string{wishlistsection.WishlistTemplateSectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlisttemplatesection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsuo.mutation.WishlistTemplateSectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wishlistsection.WishlistTemplateSectionTable,
			Columns: []string{wishlistsection.WishlistTemplateSectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wishlisttemplatesection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WishlistSection{config: wsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wishlistsection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wsuo.mutation.done = true
	return _node, nil
}
