definitions:
  usershareddao.UserEntity:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phoneNumber:
        type: string
      role:
        $ref: '#/definitions/usershareddao.UserEntityRole'
      updatedAt:
        type: string
      username:
        type: string
    type: object
  usershareddao.UserEntityDTO:
    properties:
      email:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
      role:
        $ref: '#/definitions/usershareddao.UserEntityRole'
      username:
        type: string
    type: object
  usershareddao.UserEntityRole:
    enum:
    - User
    - Admin
    type: string
    x-enum-varnames:
    - UserRole
    - AdminRole
info:
  contact: {}
  description: User Service API
  title: User Service
  version: "1.0"
paths:
  /api/users/user/v1:
    get:
      description: Returns all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usershareddao.UserEntity'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "501":
          description: Not Implemented
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all users
      tags:
      - user
    post:
      description: Creates user
      parameters:
      - description: User data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/usershareddao.UserEntityDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usershareddao.UserEntity'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - user
  /api/users/user/v1/{id}:
    get:
      description: Returns user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usershareddao.UserEntity'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user by ID
      tags:
      - user
    put:
      description: Updates user data
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/usershareddao.UserEntityDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usershareddao.UserEntity'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update user data
      tags:
      - user
swagger: "2.0"
